# Generated by Django 2.1.7 on 2019-03-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20190325_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsingRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('inforname', models.CharField(max_length=32)),
            ],
        ),
    ]
