# Generated by Django 2.1.7 on 2019-03-27 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_usingrecords'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsingRecords',
        ),
    ]
