# Generated by Django 2.1.7 on 2019-03-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_delete_usingrecords'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordViaUsername',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('search', models.CharField(max_length=64)),
            ],
        ),
    ]
