# Generated by Django 2.1.7 on 2019-04-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_recordviausername'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonClick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antique1', models.CharField(max_length=64)),
                ('antique2', models.CharField(max_length=64)),
                ('times', models.IntegerField()),
            ],
        ),
    ]
