# Generated by Django 2.1.7 on 2019-04-23 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_buttonclick'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buttonclick',
            old_name='times',
            new_name='time',
        ),
    ]
