# Generated by Django 2.1.7 on 2019-04-24 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20190423_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MainAntique', models.CharField(max_length=64)),
                ('recommend', models.CharField(max_length=64)),
                ('antique1', models.CharField(max_length=64)),
                ('antique2', models.CharField(max_length=64)),
                ('antique3', models.CharField(max_length=64)),
                ('antique4', models.CharField(max_length=64)),
                ('antique5', models.CharField(max_length=64)),
                ('antique6', models.CharField(max_length=64)),
                ('antique7', models.CharField(max_length=64)),
                ('time', models.IntegerField()),
            ],
        ),
    ]
