# Generated by Django 2.1.7 on 2019-05-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_recommendrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('search', models.CharField(max_length=128)),
                ('time', models.IntegerField()),
                ('valid', models.IntegerField()),
            ],
        ),
    ]
